id: deployments.file.read
description: Get contents of a single deployment file
permission: deployments.read
request:
  method: GET
  path: /v7/deployments/{id}/files/{fileId}
inputs:
  - name: id
    type: string
    required: true
    location: path
  - name: fileId
    type: string
    required: true
    location: path
  - name: teamId
    type: string
    location: query
errors:
  "401": {code: auth_failed}
  "404": {code: not_found}
